name: Run Cypress Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress and dependencies
        uses: cypress-io/github-action@v6
        with:
          build: npm run build  # Optional build command
          start: npm start  # Optional start command
          wait-on: 'http://localhost:5173/'  # Adjust as per your application's URL
          wait-on-timeout: '240'  # Optional wait timeout

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: 'run'
          record: true  # Optional: Record test results in the Cypress Dashboard
          parallel: true  # Optional: Run tests in parallel
          group: 'Production'  # Optional: Specify test group in Cypress Dashboard
